-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: WatchAnalytics/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE watch_tracking_user (
  tracking_timestamp TIMESTAMPTZ NOT NULL,
  user_id INT NOT NULL,
  num_watches INT NOT NULL,
  num_pending INT NOT NULL,
  event_notes VARCHAR(63) DEFAULT NULL
);

CREATE INDEX watch_tracking_user_datapoint ON watch_tracking_user (tracking_timestamp, user_id);

CREATE INDEX watch_tracking_user_user ON watch_tracking_user (user_id);

CREATE INDEX watch_tracking_user_timestamp ON watch_tracking_user (tracking_timestamp);


CREATE TABLE watch_tracking_page (
  tracking_timestamp TIMESTAMPTZ NOT NULL,
  page_id INT NOT NULL,
  num_watches INT NOT NULL,
  num_reviewed INT NOT NULL,
  event_notes VARCHAR(63) DEFAULT NULL
);

CREATE UNIQUE INDEX watch_tracking_page_datapoint ON watch_tracking_page (tracking_timestamp, page_id);

CREATE INDEX watch_tracking_page_page ON watch_tracking_page (page_id);

CREATE INDEX watch_tracking_page_timestamp ON watch_tracking_page (tracking_timestamp);


CREATE TABLE watch_tracking_wiki (
  tracking_timestamp TIMESTAMPTZ NOT NULL,
  num_pages INT NOT NULL,
  num_watches INT NOT NULL,
  num_pending INT NOT NULL,
  max_pending_minutes INT NOT NULL,
  avg_pending_minutes INT NOT NULL,
  num_unwatched INT NOT NULL,
  num_one_watched INT NOT NULL,
  num_unreviewed INT NOT NULL,
  num_one_reviewed INT NOT NULL,
  content_num_pages INT NOT NULL,
  content_num_watches INT NOT NULL,
  content_num_pending INT NOT NULL,
  content_max_pending_minutes INT NOT NULL,
  content_avg_pending_minutes INT NOT NULL,
  content_num_unwatched INT NOT NULL,
  content_num_one_watched INT NOT NULL,
  content_num_unreviewed INT NOT NULL,
  content_num_one_reviewed INT NOT NULL,
  event_notes VARCHAR(63) DEFAULT NULL
);

CREATE UNIQUE INDEX watch_tracking_wiki_datapoint ON watch_tracking_wiki (tracking_timestamp);
